databases:
  - name: datasetauditor-db
    plan: free
    databaseName: datachecker
    user: datachecker

services:
  - type: web
    name: datasetauditor-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datasetauditor-db
          property: connectionString
      - key: CKAN_API_KEY
        sync: false
